spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cryptohds
    username: root
    password: cryptohds

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  logging:
    level:
      org.springframework.web: WARN
      guru.springframework.controllers: WARN
      org.hibernate: WARN