version: '2'
services:
    cryptohds:
        image: cryptohds
        environment:
            #- SPRING_DATASOURCE_URL=jdbc:mysql://teste-mysql:3306/teste?useUnicode=true&characterEncoding=utf8&useSSL=false
            - APP_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 80:80
    cryptohds-mysql:
        extends:
            file: mysql.yml
            service: cryptohds-mysql
